services:
    # server
    web:
        image: garyclarke/php-framework-web
        volumes:
            - ./public:/var/www/html/public
        ports:
            - "80:80"
    # application
    app:
        image: garyclarke/php-framework-app
        volumes:
            - .:/var/www/html
        extra_hosts:
            - host.docker.internal:host-gateway
